language: go
sudo: false
go: 1.6.2
os: osx
notifications:
  email: false
branches:
  only:
    - master
  except:
    - gh-pages
deploy:
  provider: releases
  api_key: {{ GH_TOKEN }}
  file: dist/chrome-bookmarks.alfredworkflow
  skip_cleanup: true
  on:
    tags: true
before_install:
  - unset GO15VENDOREXPERIMENT
script:
  - make clean
  - make vet
  - make coveralls
  - make workflow
