# GH_TOKEN
# COVERALLS_TOKEN
language: go
sudo: false
go:
  - tip
os:
  - osx
notifications:
  email: false
branches:
  only:
    - master
  except:
    - gh-pages
deploy:
  provider: releases
  api_key: {{ GH_TOKEN }}
  file: dist/chrome-bookmarks.alfredworkflow
  skip_cleanup: true
  on:
    tags: true
script:
  - make clean
after_script:
  - make coveralls
  - make workflow
