language: go
sudo: false
go:
  - tip
os:
  - osx
notifications:
  email: false
branches:
  only:
    - master
  except:
    - gh-pages
deploy:
  provider: releases
  api_key: {{ GH_TOKEN }}
  file: dist/chrome-bookmarks.alfredworkflow
  skip_cleanup: true
  on:
    tags: true
before_script:
  - make lint
script:
  - make clean
  - make coveralls
  - make workflow
