language: go
sudo: false
go: 1.6.2
os: osx
notifications:
  email: false
branches:
  only:
    - master
    - ^v\d+\.\d+\.\d+[\-[\dA-Za-z\-\.]+]?[\+[\dA-Za-z\-\.]+]?$
  except:
    - gh-pages
deploy:
  provider: releases
  api_key: {{ GH_TOKEN }}
  file: dist/chrome-bookmarks.alfredworkflow
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
install:
  - make restore
script:
  - make clean
  - make lint
  - make coveralls
  - make workflow
